from babelecho.transcript_cleaning import clean_timed_transcript_text


def test_clean_timed_transcript_text_removes_vtt_metadata_and_cue_settings():
    content = """WEBVTT

NOTE generated by a caption service

STYLE
::cue { color: white }

REGION
id:fred

00:00:00.000 --> 00:00:01.000 align:start position:0%
Hello from the episode.
"""

    cleaned = clean_timed_transcript_text(content, "vtt", merge_short_cues=False)

    assert cleaned == (
        "WEBVTT\n\n"
        "00:00:00.000 --> 00:00:01.000\n"
        "Hello from the episode.\n"
    )


def test_clean_timed_transcript_text_deduplicates_repeated_caption_lines():
    content = """WEBVTT

00:00:00.000 --> 00:00:01.000
AI agents are useful
AI agents are useful
"""

    cleaned = clean_timed_transcript_text(content, "vtt", merge_short_cues=False)

    assert cleaned == (
        "WEBVTT\n\n"
        "00:00:00.000 --> 00:00:01.000\n"
        "AI agents are useful\n"
    )


def test_clean_timed_transcript_text_decodes_html_entities():
    content = """WEBVTT

00:00:00.000 --> 00:00:01.000
AI&nbsp;agents&nbsp;&nbsp;call tools.
"""

    cleaned = clean_timed_transcript_text(content, "vtt", merge_short_cues=False)

    assert cleaned == (
        "WEBVTT\n\n"
        "00:00:00.000 --> 00:00:01.000\n"
        "AI agents call tools.\n"
    )


def test_clean_timed_transcript_text_removes_inline_youtube_timing_markup():
    content = """WEBVTT

00:00:00.000 --> 00:00:04.000
Our job is being available wherever customers<00:00:02.680><c> are.</c>
"""

    cleaned = clean_timed_transcript_text(content, "vtt", merge_short_cues=False)

    assert cleaned == (
        "WEBVTT\n\n"
        "00:00:00.000 --> 00:00:04.000\n"
        "Our job is being available wherever customers are.\n"
    )


def test_clean_timed_transcript_text_removes_speaker_arrows():
    content = """WEBVTT

00:00:00.000 --> 00:00:04.000
>> Thank you, Mr. President. My question is about Iran or >> where are you from?
"""

    cleaned = clean_timed_transcript_text(content, "vtt", merge_short_cues=False)

    assert cleaned == (
        "WEBVTT\n\n"
        "00:00:00.000 --> 00:00:04.000\n"
        "Thank you, Mr. President. My question is about Iran or where are you from?\n"
    )


def test_clean_timed_transcript_text_removes_rolling_caption_overlap():
    content = """WEBVTT

00:00:00.000 --> 00:00:02.270
Our<00:00:00.640><c> job</c><00:00:01.040><c> is</c><00:00:01.280><c> being</c><00:00:01.600><c> available</c><00:00:02.040><c> wherever</c>

00:00:02.270 --> 00:00:02.280
Our job is being available wherever

00:00:02.280 --> 00:00:04.350
Our job is being available wherever customers<00:00:02.680><c> are.</c><00:00:03.040><c> In</c><00:00:03.160><c> the</c><00:00:03.240><c> 1950s,</c><00:00:04.000><c> that</c><00:00:04.160><c> meant</c>

00:00:04.350 --> 00:00:04.360
customers are. In the 1950s, that meant

00:00:04.360 --> 00:00:06.150
customers are. In the 1950s, that meant building<00:00:04.600><c> a</c><00:00:04.640><c> bank</c><00:00:04.880><c> branch.</c>
"""

    cleaned = clean_timed_transcript_text(content, "vtt")

    assert cleaned == (
        "WEBVTT\n\n"
        "00:00:00.000 --> 00:00:06.150\n"
        "Our job is being available wherever customers are. "
        "In the 1950s, that meant building a bank branch.\n"
    )


def test_clean_timed_transcript_text_merges_fragmented_youtube_cues():
    content = """WEBVTT

00:00:00.000 --> 00:00:01.000
AI agents

00:00:01.200 --> 00:00:02.000
can call tools

00:00:02.300 --> 00:00:03.000
and reason over results.

00:00:06.000 --> 00:00:07.000
Next sentence starts here.
"""

    cleaned = clean_timed_transcript_text(content, "vtt")

    assert cleaned == (
        "WEBVTT\n\n"
        "00:00:00.000 --> 00:00:03.000\n"
        "AI agents can call tools and reason over results.\n\n"
        "00:00:06.000 --> 00:00:07.000\n"
        "Next sentence starts here.\n"
    )


def test_clean_timed_transcript_text_does_not_merge_across_speaker_labels():
    content = """WEBVTT

00:00:00.000 --> 00:00:01.000
Host: Welcome

00:00:01.200 --> 00:00:02.000
Guest: Thanks for having me.
"""

    cleaned = clean_timed_transcript_text(content, "vtt")

    assert cleaned == (
        "WEBVTT\n\n"
        "00:00:00.000 --> 00:00:01.000\n"
        "Host: Welcome\n\n"
        "00:00:01.200 --> 00:00:02.000\n"
        "Guest: Thanks for having me.\n"
    )
